import {Customer} from '../model';
import {TypeSchemaSql} from './type.schema';

export const SchemaCustomer: TypeSchemaSql<Customer> = {
  name: 'Customer',
  primaryKey: 'Makhachhang',
  indexs: ['Makhuvuc'],
  properties: {
    Chisocu: 'INTEGER',
    Chisodu: 'VARCHAR',
    Chisomoi: 'INTEGER',
    Diachi: 'VARCHAR',
    Doituonggia: 'VARCHAR',
    Ghichu: 'VARCHAR',
    Ghichuoffline: 'VARCHAR',
    Khanangdongho: 'VARCHAR',
    Latitude: 'VARCHAR',
    Longitude: 'VARCHAR',
    Lydodutchi: 'VARCHAR',
    Madoituonggia: 'VARCHAR',
    Madongho: 'VARCHAR',
    Makhachhang: 'VARCHAR',
    Makhuvuc: 'VARCHAR',
    Manvghiso: 'VARCHAR',
    Maso: 'VARCHAR',
    Mathoiky: 'INTEGER',
    Muctieuthu: 'INTEGER',
    Ngaydocmoi: 'VARCHAR',
    Picture: 'VARCHAR',
    Qrcode: 'VARCHAR',
    Sodienthoai: 'VARCHAR',
    Tenkhachhang: 'VARCHAR',
    Tennvghiso: 'VARCHAR',
    Tieuthu1: 'INTEGER',
    Tieuthu2: 'INTEGER',
    Tieuthu3: 'INTEGER',
    Trangthai: 'VARCHAR',
    Dongbo: 'BOOLEAN',
  },
};
